// export { default as Cart } from "./Cart";
export { default as LoginOrRegister } from "./LoginOrRegister";
export { default as SingleProductView } from "./SingleProductView";
export { default as AllProductViews } from "./AllProductViews";
export { default as Title } from "./Title";
export { default as Nav } from "./Nav";
export { default as Profile } from "./Profile";
export { default as AdminProfile } from "./AdminProfile";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as Cart } from "./Cart";
export { default as AddNewProduct } from "./AddNewProduct";
export { default as EditProduct } from "./EditProduct";
